### ISSUE TITLE
动画

### ISSUE THREAD

**Issue by rcj60560** [infinite-Zh/PieChart#2]
@infinite-Zh 你好 我看了你的效果感觉很厉害，有个问题 就是能不能个设置下点击圆环的时候 添加一个动画 让选中的index 圆环变大一点

**Comment by infinite-Zh** [comment]
> @infinite-Zh 你好 我看了你的效果感觉很厉害，有个问题 就是能不能个设置下点击圆环的时候 添加一个动画 让选中的index 圆环变大一点

你好，点击动画效果写了个简单的实现，您可以看一下

**Comment by rcj60560** [comment]
@infinite-Zh 我跑了下代码 我也出现了跟你一样的问题 ，您看最后项目底部的gif，点击变大的时候文字方向有问题了，还有就是我想实现的效果是，点击的时候外切圆半径变大 就是现在这样的，里面也半径也变小，就是同时向外面变大 里面也变小

**Comment by infinite-Zh** [comment]
> @infinite-Zh 我跑了下代码 我也出现了跟你一样的问题 ，您看最后项目底部的gif，点击变大的时候文字方向有问题了，还有就是我想实现的效果是，点击的时候外切圆半径变大 就是现在这样的，里面也半径也变小，就是同时向外面变大 里面也变小

文字方向会变化的bug已经修复了，你说的动画效果，是说点击的时候，被点击的部分整体向外移动一下吗？[dev-rcj](https://github.com/infinite-Zh/PieChart/tree/dev-rcj)

**Comment by rcj60560** [comment]
@infinite-Zh  可能我描述不清楚我想要的效果，方便加微信吗 我给你看看ios效果 安卓效果 我暂时没想到其他办法

**Comment by infinite-Zh** [comment]
> @infinite-Zh 可能我描述不清楚我想要的效果，方便加微信吗 我给你看看ios效果 安卓效果 我暂时没想到其他办法

我wx号：infinite_infinite
